### ISSUE TITLE
I want to treat repositories less than organization

### ISSUE THREAD

**Issue by yoshiaki-u** [StackStorm-Exchange/stackstorm-github#11]
I want to treat repositories less than organization.
For example:
 https://mygithub.mycompany.com/myOrganization/myProject
In this situation I think that I cannot access it. Therefore I performed the following changes.
Is this a good change?
/github/sensors/github_repository_sensor.py

    @@ -41,9 +46,15 @@ class GithubRepositorySensor(PollingSensor):
                 raise ValueError('GithubRepositorySensor should have atleast 1 repository.')
    
             for repository_dict in repositories:
    -            user = self._client.get_user(repository_dict['user'])
    -            repository = user.get_repo(repository_dict['name'])
    -            self._repositories.append((repository_dict['name'], repository))
    +            if ('name' in repository_dict) and ('user' in repository_dict):
    +                user = self._client.get_user(repository_dict['user'])
    +                repository = user.get_repo(repository_dict['name'])
    +                self._repositories.append((repository_dict['name'], repository))
    +            else:
    +                org = self._client.get_organization(repository_dict['org'])
    +                repository = org.get_repo(repository_dict['repo'])
    +                self._repositories.append((repository_dict['repo'], repository))
    +        #self._logger.critical(self._repositories)

**Comment by LindsayHill** [comment]
I don't think this is required. Are you having problems monitoring a repository under an organization? 

From my testing, I have no problems monitoring a repo like that, for example StackStorm/st2?

In your `github.yaml` file, you should be able to set something like this:

```yaml
repository_sensor:
  event_type_whitelist:
    - "IssuesEvent"
    - "IssueCommentEvent"
    - "ForkEvent"
    - "WatchEvent"
    - "ReleaseEvent"
    - "PushEvent"

  repositories:
    -
      user: "myOrganization"
      name: "myProject"
```

If that does not work, what happens if you run something like this:

```python
from github import Github
client=Github(None)
user=client.get_user('myOrganisation')
repository=user.get_repo('myProject')
type(repository)
```

(You may need some additional code above to use your internal Github Enterprise server)
